NUMPY

NumPy (Numerical Python) is a Python library used for fast numerical computations using multidimensional arrays.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, 1/0, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

• NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.    

• The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 

• NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such Operations are executed more efficiently and with less code than is possible using Python's built-in sequences. 

• A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [ ]:
import numpy as np

Creation of NumPy Arrays

In [4]:
a = np.array([2,4,6])

print(a)

[2 4 6]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
#dtype of array
print(a.dtype)
b = np.array([1, 2, 3], dtype=np.float64)
print(b.dtype)
print(b)
c= np.array([1, 2, 3], dtype=np.complex128)
print(c.dtype)
print(c)

int32
float64
[1. 2. 3.]
complex128
[1.+0.j 2.+0.j 3.+0.j]


In [22]:
c= np.arange(0,10,2) #start, stop, step
print(c)

[0 2 4 6 8]


In [25]:
x=np.arange(10, 30, 5)
print(x)
print(np.arange(10, 30, 5).reshape(2, 2))

[10 15 20 25]
[[10 15]
 [20 25]]


In [28]:
np.ones((3, 4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [29]:
np.zeros((3, 4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [40]:
# 3x4 array of random floats in [0, 1)
np.random.random((3, 4))


array([[0.74515661, 0.43991439, 0.09280418, 0.17296458],
       [0.23223728, 0.24927543, 0.33033073, 0.37697386],
       [0.44378285, 0.86065624, 0.01803041, 0.85014058]])

In [41]:
np.random.randint(1, 10, size=(3, 4))

array([[6, 7, 1, 2],
       [4, 9, 6, 3],
       [2, 5, 7, 8]])

In [46]:
np.linspace(0, 100, 5, dtype=np.int64)

array([  0,  25,  50,  75, 100], dtype=int64)

In [47]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#ndim
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print("dimension of c:", c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension of c: 3


In [52]:
#shape
print("shape of c:", c.shape)

shape of c: (2, 2, 2)


In [53]:
#size
print("size of c:", c.size)

size of c: 8


In [54]:
#itemsize
print("itemsize of c:", c.itemsize)

itemsize of c: 4


In [57]:
#astype
d = np.array([1, 2, 3, 4, 5])
print(d.astype(float))

[1. 2. 3. 4. 5.]


Operations on NumPy Arrays

In [58]:
#scalar
a = np.array([1, 2, 3, 4, 5])
print(a + 5)

[ 6  7  8  9 10]


In [60]:
print(a *5)

[ 5 10 15 20 25]


In [61]:
print(a ** 5)

[   1   32  243 1024 3125]


In [68]:
a=np.array([[1,2,4,5],[5,6,7,8],[9,10,11,12]])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  4  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
print(a ==5)

[[False False False  True]
 [ True False False False]
 [False False False False]]


In [70]:
print (a >1)

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [71]:
a+b


array([[ 2,  4,  7,  9],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [72]:
a ** b

array([[         1,          4,         64,        625],
       [      3125,      46656,     823543,   16777216],
       [ 387420489, 1410065408, 1843829075, -251658240]])

In [84]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(np.round(c*100))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[100 200]
  [300 400]]

 [[500 600]
  [700 800]]]


In [85]:
print(np.prod(c, axis=0))

[[ 5 12]
 [21 32]]


In [88]:
print(np.sqrt(c))

[[[1.         1.41421356]
  [1.73205081 2.        ]]

 [[2.23606798 2.44948974]
  [2.64575131 2.82842712]]]


In [89]:
np.max(c, axis=0)

array([[5, 6],
       [7, 8]])

In [90]:
np.min(c, axis=0)

array([[1, 2],
       [3, 4]])

In [91]:
np.sum(c, axis=0)

array([[ 6,  8],
       [10, 12]])

mean/median/standard deviation/variance

In [94]:
np.mean(c, axis=1)

array([[2., 3.],
       [6., 7.]])

In [96]:
np.median(c, axis=1)

array([[2., 3.],
       [6., 7.]])

In [97]:
np.std(c, axis=1)

array([[1., 1.],
       [1., 1.]])

In [98]:
np.var(c, axis=1)

array([[1., 1.],
       [1., 1.]])