In [11]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print("shape of a is ", a.shape)
print("transpose of a is")
a = a.transpose()
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of a is  (3, 3)
transpose of a is
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
b = np.array([2, 3, 4])
print(b)

[2 3 4]
