NUMPY

NumPy (Numerical Python) is a Python library used for fast numerical computations using multidimensional arrays.

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, 1/0, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

• NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.    

• The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 

• NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such Operations are executed more efficiently and with less code than is possible using Python's built-in sequences. 

• A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
import numpy as np

Creation of NumPy Arrays

In [3]:
a = np.array([2,4,6])

print(a)

[2 4 6]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
#dtype of array
print(a.dtype)
b = np.array([1, 2, 3], dtype=np.float64)
print(b.dtype)
print(b)
c= np.array([1, 2, 3], dtype=np.complex128)
print(c.dtype)
print(c)

int32
float64
[1. 2. 3.]
complex128
[1.+0.j 2.+0.j 3.+0.j]


In [7]:
c= np.arange(0,10,2) #start, stop, step
print(c)

[0 2 4 6 8]


In [8]:
x=np.arange(10, 30, 5)
print(x)
print(np.arange(10, 30, 5).reshape(2, 2))

[10 15 20 25]
[[10 15]
 [20 25]]


In [9]:
np.ones((3, 4), dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [10]:
np.zeros((3, 4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [11]:
# 3x4 array of random floats in [0, 1)
np.random.random((3, 4))


array([[0.58563485, 0.50455477, 0.88563389, 0.98161095],
       [0.53552017, 0.89668358, 0.67932403, 0.55108159],
       [0.22202936, 0.41535679, 0.65241849, 0.77902895]])

In [12]:
np.random.randint(1, 10, size=(3, 4))

array([[2, 9, 9, 7],
       [9, 1, 4, 6],
       [9, 8, 6, 1]])

In [13]:
np.linspace(0, 100, 5, dtype=np.int64)

array([  0,  25,  50,  75, 100], dtype=int64)

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#ndim
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print("dimension of c:", c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimension of c: 3


In [16]:
#shape
print("shape of c:", c.shape)

shape of c: (2, 2, 2)


In [17]:
#size
print("size of c:", c.size)

size of c: 8


In [18]:
#itemsize
print("itemsize of c:", c.itemsize)

itemsize of c: 4


In [19]:
#astype
d = np.array([1, 2, 3, 4, 5])
print(d.astype(float))

[1. 2. 3. 4. 5.]


Operations on NumPy Arrays

In [20]:
#scalar
a = np.array([1, 2, 3, 4, 5])
print(a + 5)

[ 6  7  8  9 10]


In [21]:
print(a *5)

[ 5 10 15 20 25]


In [22]:
print(a ** 5)

[   1   32  243 1024 3125]


In [23]:
a=np.array([[1,2,4,5],[5,6,7,8],[9,10,11,12]])
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  4  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(a ==5)

[[False False False  True]
 [ True False False False]
 [False False False False]]


In [25]:
print (a >1)

[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [26]:
a+b


array([[ 2,  4,  7,  9],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [27]:
a ** b

array([[         1,          4,         64,        625],
       [      3125,      46656,     823543,   16777216],
       [ 387420489, 1410065408, 1843829075, -251658240]])

In [28]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(np.round(c*100))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[100 200]
  [300 400]]

 [[500 600]
  [700 800]]]


In [29]:
print(np.prod(c, axis=0))

[[ 5 12]
 [21 32]]


In [30]:
print(np.sqrt(c))

[[[1.         1.41421356]
  [1.73205081 2.        ]]

 [[2.23606798 2.44948974]
  [2.64575131 2.82842712]]]


In [31]:
np.max(c, axis=0)

array([[5, 6],
       [7, 8]])

In [32]:
np.min(c, axis=0)

array([[1, 2],
       [3, 4]])

In [33]:
np.sum(c, axis=0)

array([[ 6,  8],
       [10, 12]])

mean/median/standard deviation/variance

In [44]:
c= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
d= np.array([[1,2,3,4],[5,6,7,8]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]


In [41]:
#axis=0 means:
#Take the mean between the two 2×2 matrices.
np.mean(c, axis=0)

array([[3., 4.],
       [5., 6.]])

In [46]:
#Axis 1 → rows inside each matrix
print(np.mean(c, axis=1))
print(d.mean(axis=0))

[[2. 3.]
 [6. 7.]]
[3. 4. 5. 6.]


In [49]:
#Axis 2 → columns inside each matrix
print(np.mean(c, axis=2))
print(print(d.mean(axis=1)))

[[1.5 3.5]
 [5.5 7.5]]
[2.5 6.5]
None


In [50]:
np.median(d, axis=1)

array([2.5, 6.5])

In [36]:
np.std(c, axis=1)

array([[1., 1.],
       [1., 1.]])

In [51]:
np.std(d, axis=1)

array([1.11803399, 1.11803399])

In [37]:
np.var(c, axis=1)

array([[1., 1.],
       [1., 1.]])

| Python List                  | NumPy ndarray                     |
| ---------------------------- | --------------------------------- |
| Slower                       | Faster                            |
| Different data types allowed | Usually one data type             |
| More memory                  | Less memory                       |
| Poor for numerical computing | Optimized for numerical computing |


NumPy uses vectorized operations implemented in optimized C code. This makes computations much faster than Python loops while also making the code shorter, cleaner, and easier to maintain.

Trigonometric functions are available in NumPy. These functions operate on angles expressed in radians. The following table lists the trigonometric functions available in NumPy.

In [55]:
#Trigonometruc functions
np.sin(d)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [54]:
np.tan(c)

array([[[ 1.55740772, -2.18503986],
        [-0.14254654,  1.15782128]],

       [[-3.38051501, -0.29100619],
        [ 0.87144798, -6.79971146]]])

In [66]:
#Dot product
a1 = np.arange(0,10,1).reshape(2,5)
a2 = np.arange(100,200,10).reshape(5,2)
print("a1:")

print(a1)
print(" ")
print("a2:")

print(a2)
print(" ")
print("Dot product:")

print(np.dot(a1, a2))


a1:
[[0 1 2 3 4]
 [5 6 7 8 9]]
 
a2:
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
 
Dot product:
[[1600 1700]
 [5100 5450]]


In [68]:
#log and exponential functions
np.log(d)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])

In [69]:
np.exp(d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [76]:
#rounding
y=np.random.rand(2,3)*100
print(y)
y.round(2)

[[58.35401503 53.10791379 40.9844335 ]
 [67.01552744 89.88475195 54.43431948]]


array([[58.35, 53.11, 40.98],
       [67.02, 89.88, 54.43]])

In [81]:
#floor and ceil
y=np.random.rand(3,3)*100
print(y)
print("Floor:")
print(np.floor(y))
print("Ceil:")
print(np.ceil(y))   

[[61.89224709 31.55875616  6.08850928]
 [46.26875278 20.2209373  93.49909739]
 [75.00741865 86.68493843 82.94534307]]
Floor:
[[61. 31.  6.]
 [46. 20. 93.]
 [75. 86. 82.]]
Ceil:
[[62. 32.  7.]
 [47. 21. 94.]
 [76. 87. 83.]]


Indexing, Slicing and Iterating

In [85]:
a1= np.arange(10)
a2= np.arange(12).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)


a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
#accessing elements
a1[0]

0

In [92]:
#accessing elements from 2D array in reverse direction
a2[-1, 0]

8

In [93]:
a3[1,0,1]

5

In [94]:
a3[0,1,0]

2

In [95]:
a1[0:5]

array([0, 1, 2, 3, 4])

In [96]:
a1[2:8:2]

array([2, 4, 6])

In [98]:
print(a2)
a2[0,:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 1, 2, 3])

In [99]:
a2[1,2:]

array([6, 7])

In [100]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [101]:
a2[:,2]

array([ 2,  6, 10])

In [104]:
a2[1:,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [105]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [108]:
a2[::2,0]

array([0, 8])

In [109]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [113]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [114]:
#accessing elements with slicing from 3D array
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])